### ISSUE TITLE
Double Tap E Causes Horn Lock

### ISSUE THREAD

**Issue by JackDUpModZ** [BerkieBb/pma-sirensync#1]
When pressing E twice sometimes it will cause the horn to lock on until pressed again, If you press very quickly it wont lock but 2 presses in a row it will stay locked.

**Comment by BerkieBb** [comment]
I can't seem to reproduce the issue, are you able to provide a video?

**Comment by BerkieBb** [comment]
https://github.com/BerkieBb/pma-sirensync/commit/419a347ecf43d114e476db2c7ab4765c7bf6320b
I did make this commit, I don't know if it helps, but if it does, let me know

**Comment by JackDUpModZ** [comment]
> [419a347](https://github.com/BerkieBb/pma-sirensync/commit/419a347ecf43d114e476db2c7ab4765c7bf6320b) I did make this commit, I don't know if it helps, but if it does, let me know

Seems to have resolved it for the most part, It's only happening maybe 1 in 10 times now but you have to instantly tap the button twice. Thanks for the fix :)
