### ISSUE TITLE
Just one addon car has default sirens

### ISSUE THREAD

**Issue by Zzeyy** [BerkieBb/pma-sirensync#10]
I have like 5 addon vehicles with sirens and only 1 of them does not follow the script.
What should I do?

**Comment by BerkieBb** [comment]
What do you mean?

**Comment by Zzeyy** [comment]
One addon car has default controls. No J K L, just E.

**Comment by BerkieBb** [comment]
That means the car isn't an emergency vehicle

**Comment by Zzeyy** [comment]
Ambulance is not an emergency vehicle?

**Comment by BerkieBb** [comment]
The only vehicles that work are emergency vehicles, which is defined by the vehicle class

**Comment by BerkieBb** [comment]
So the vehicles.meta of that vehicle is probably wrong

**Comment by Zzeyy** [comment]
How am I supposed to change vehicles.meta of a vanilla vehicle?

**Comment by BerkieBb** [comment]
You can re-stream it, but the vanilla vehicles should work though, let me check

**Comment by Zzeyy** [comment]
The addon vehicle was in fact set improperly, to sedan.

**Comment by BerkieBb** [comment]
The default ambulance in the game does have the emergency vehicle class

**Comment by BerkieBb** [comment]
Are you sure you're not using an addon vehicle instead or the vehicles.meta of it is re-streamed?

**Comment by Zzeyy** [comment]
I'm sure I'm not using an addon vehicle. I'm using a vehicle of which spawn code is `ambulance`.

**Comment by Zzeyy** [comment]
It's weird. When I spawn an ambulance it's working fine, but if I use the one in hospital's garage it does not work.

**Comment by Zzeyy** [comment]
So the issue is resolved. Thanks for telling me about the class.

**Comment by BerkieBb** [comment]
Then that vehicle may be another model with the wrong vehicle class

**Comment by Zzeyy** [comment]
> Then that vehicle may be another model with the wrong vehicle class

I don't think so. I know what addon vehicles I got on my server.
Probably the way the ambulance got stored is messed up.

**Comment by BerkieBb** [comment]
> Probably the way the ambulance got stored is messed up.

Could be, I don't really know, if I come across this issue again, I'll do an investigation on it
