### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by DogsGoBark** [BerkieBb/pma-sirensync#2]
Does it support the use of [wm server sirens](https://github.com/Walsheyy/WMServerSirens)?

```lua
RequestScriptAudioBank("DLC_WMSIRENS\\SIRENPACK_ONE", false)
PlaySoundFromEntity(snd_lxsiren[veh], "SIREN_ALPHA", veh, "DLC_WMSIRENS_SOUNDSET", 0, 0)
PlaySoundFromEntity(snd_lxsiren[veh], "SIREN_BRAVO", veh, "DLC_WMSIRENS_SOUNDSET", 0, 0)
PlaySoundFromEntity(snd_lxsiren[veh], "SIREN_CHARLIE", veh, "DLC_WMSIRENS_SOUNDSET", 0, 0)
````

**Comment by BerkieBb** [comment]
Yes it does, the sound that you want can be replaced on a vehicle from the config, but that does require you to build the resource again

**Comment by DogsGoBark** [comment]
So I assume something like this?

```ts
export const HornOverride: Map<number, string> = new Map<number, string>()
	.set(GetHashKey("police3"), "DLC_WMSIRENS\\SIRENPACK_ONE");

export const PrimarySirenOverride: Map<number, string | string[]> = new Map<number, string | string[]>()
	.set(GetHashKey("police3"), ["SIREN_ALPHA", "SIREN_BRAVO", "SIREN_CHARLIE"]);

export const Debug: boolean = false;
```

**Comment by DogsGoBark** [comment]
> The primary sound override is good, but the horn override is for the horn of the vehicle, not an audio bank

How will it know to use that DLC?

**Comment by BerkieBb** [comment]
I guess you'd have to request it seperatelt then, bht I'll take a look tomorrow on adding something for that

**Comment by BerkieBb** [comment]
Added in https://github.com/BerkieBb/pma-sirensync/commit/296a1838705ffb996968a473fffaedb3a7dcc29a

**Comment by BerkieBb** [comment]
https://github.com/BerkieBb/pma-sirensync/commit/8d8bf1e5871085e64939cba3319a62cb1aea0795 as a followup as I forgot some things
