### ISSUE TITLE
Siren are not sync outside vehicle

### ISSUE THREAD

**Issue by Cyril-Beeckman** [BerkieBb/pma-sirensync#3]
Description :
- You go in vehicle and enable lights and sirens
- You go out of vehicle
- You can hear siren
- Other people stop hearing siren when you leave vehicle

**Comment by varkosqc** [comment]
I have the same problem with the lasted commit!

**Comment by BerkieBb** [comment]
I noticed a typo yeah on the server side

**Comment by BerkieBb** [comment]
https://github.com/BerkieBb/pma-sirensync/releases/tag/1.0.4
Here is the fix, thanks for the report!
