### ISSUE TITLE
Can't turn off sirens IF

### ISSUE THREAD

**Issue by iSentrie** [BerkieBb/pma-sirensync#5]
Repro for a sirens bug, which breaks it from turning off.

1. Turn on siren lighs
2. Press `Arrow up`
3. Press ` , `
4. Press `Arrow up`
5. You should be unable to turn off sirens.

**Comment by BerkieBb** [comment]
Yeah seems like the siren from the arrow up doesn't stop, I'll fix this later, but to stop the sirens from the comma key, just press the key `.`

**Comment by iSentrie** [comment]
`Arrow up` should be a toggle and it would be fine.

**Comment by BerkieBb** [comment]
After some feedback I made it a cycle through sounds only, it won't turm them off

**Comment by BerkieBb** [comment]
It should only turn off when disabling the lights

**Comment by BerkieBb** [comment]
Fixed the issue here https://github.com/BerkieBb/pma-sirensync/commit/d59de557aa12ed138978fa3d0c628ac5bc7713ab
