### ISSUE TITLE
In the shared/shared.ts file there's no way to change the controls

### ISSUE THREAD

**Issue by Zzeyy** [BerkieBb/pma-sirensync#6]
Hi, I would like to control the sirens by using **E** to enable them and **Q** to cycle through all the variants,
How am I supposed to change the controls then? Do I really have to study how to build a resource myself?
Can't you add a control config yourself, please?

**Comment by BerkieBb** [comment]
Any change to the shared.ts also requires yoi tk build the resource and you don't have to 'study' how to build the resource, I wrote how to do it step by step in the readme.

**Comment by Zzeyy** [comment]
I didn't really have the time to check the whole readme.
I hope it's easier than I think.

**Comment by Zzeyy** [comment]
I modified the controls in all of the files that the resource has, but when holding the key E the horn is not working.

**Comment by BerkieBb** [comment]
That's because it disables the default horn for emergency vehicles

**Comment by BerkieBb** [comment]
It's replaced with keymapping to the button E to play another sound

**Comment by Zzeyy** [comment]
The horn isn't working for normal vehicles, though.

**Comment by BerkieBb** [comment]
I patched that in the latest release or the one before

**Comment by Zzeyy** [comment]
Oh, okay, I'll download the new release, then.

**Comment by Zzeyy** [comment]
Also, thanks for your quick replies.
