### ISSUE TITLE
Eats permanent Performance even when not in a (emergency) car

### ISSUE THREAD

**Issue by Marc85BPG** [BerkieBb/pma-sirensync#9]
Love this - its what i searched for, so thank first...

i noticed that this resource is eating permanent performance, even when you are not in a (ermergency) car and on driver seat.
So is it possible to reduce it to be in a "emergency" car and on drivers seat to reduce the performance impact ? 

Regards

**Comment by BerkieBb** [comment]
What's 'eating performance' to you?

**Comment by Marc85BPG** [comment]
pma-sirensync.

its minimum on 0.03
even on foot and miles away from any vehicle

**Comment by BerkieBb** [comment]
0.03ms, does that sound like a lot?

**Comment by Marc85BPG** [comment]
yah when a resource is running in background, even there is no need to ? it should just sleep whenn you are not in any vehicle/ as driver ..

**Comment by BerkieBb** [comment]
0.03ms is not a lot at all, it's still running because sounds need to be synced even though you're out of the vehicle

**Comment by BerkieBb** [comment]
What would've been a lot was 0.10ms for idle

**Comment by BerkieBb** [comment]
You too!
